#!/bin/bash

export CKX_WORKSPACE=%(cwd)s
if [ -d ${CKX_WORKSPACE}/devel ]; then
  source ${CKX_WORKSPACE}/devel/setup.bash
fi
# Add the full path if android-studio is not in PATH
# Usually something like:
#   exec /opt/android-studio/bin/studio.sh
exec android-studio
