#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source ${DIR}/custom.bash

# Add the full path if android-studio is not in PATH
# Usually something like:
#   exec /opt/android-studio/bin/studio.sh
exec android-studio
