#!/usr/bin/env python

import sys
import ckx_tools
import ckx_tools.console as console

if __name__ == '__main__':
    try:
        sys.exit(ckx_tools.init_workspace())
    except Exception as e:
        console.logerror(str(e))
        sys.exit(1)
