#!/usr/bin/env python

from __future__ import print_function

import sys
from ckx_tools import make_isolated_main
import ckx_tools.console as console

if __name__ == '__main__':
    try:
        sys.exit(make_isolated_main())
    except Exception as e:
        console.logerror(str(e))
        sys.exit(1)
